### ISSUE TITLE
Dired Rsync Unmark On Completion

### ISSUE THREAD

**Issue by ghost** [stsquad/dired-rsync#32]
Copying works fine, but the folder or file marked for copying remains marked even when copying is complete. I have `Dired Rsync Unmark On Completion` set to `non-nil`.

**Comment by toto-42** [comment]
I think the bug is caused in the _dired-rsync_ function, because the dired buffer with the marks is handed to _dired-rsync--do-run_ as a string returned by _buffer-name_ and not as a Lisp object (as returned by _current-buffer_). See line 347 in [dired-rsync.el](https://github.com/stsquad/dired-rsync/blob/master/dired-rsync.el):

`(dired-rsync--do-run cmd
                         (list :marked-files sfiles
                               :dired-buffer (buffer-name)))`

_dired-rsync--do-run_ calls _dired-rsync--sentinel_, which tries to identify the buffer with _buffer-live-p_, which expects the buffer as an object, not a string. So this returns always _nil_ and the marks are not removed.

Changing _buffer-name_ to _current-buffer_ solves the problem for me. I did a few quick tests, so far I don't see any breakage by the change.

**Comment by stsquad** [comment]
I got the commit message wrong - I see what you mean about buffer-live-p. Can you check the current master is OK for you?

**Comment by toto-42** [comment]
Yes, works for me. Thx.
